### ISSUE TITLE
ArgumentError: comparison of FalseClass with BigDecimal failed

### ISSUE THREAD

**Issue by davidalejandroaguilar** [tubedude/xirr#29]
**Specs:**

* `master` branch.

**How to reproduce:**

```rb
require "date"

values = [
  [Date.parse("13 Dec 2022"), -10000.0],
  [Date.parse("13 Dec 2022"), 8000.0],
  [Date.parse("13 Dec 2022"), 2500.0],
  [Date.parse("30 Jan 2023"), 1100.0]
]

cashflow = Xirr::Cashflow.new

values.each do |date, value|
  cashflow << Xirr::Transaction.new(value, date: date)
end


cashflow.xirr
```

**Possible cause**:

Seems like `Cashflow#irr_guess` [is returning `false`](https://github.com/tubedude/xirr/blob/master/lib/xirr/cashflow.rb#L51), and that value [is then used](https://github.com/tubedude/xirr/blob/master/lib/xirr/bisection.rb#L14-L15) on `Xirr::Bisection.xirr` inside an array, which is called `min` on it, causing a comparison to `false.`

**Comment by tubedude** [comment]
The problem I see with this scenario is that when the Cashflow is compacted, the sum of values of both dates are positive and the calculation fails. If you try it in Excel it will fail too.

```
      cf = Cashflow.new
      cf << Transaction.new(-10000.0, date: '2022-12-13'.to_date)
      cf << Transaction.new( 8000.0, date: '2022-12-13'.to_date)
      cf << Transaction.new( 2500.0, date: '2022-12-13'.to_date)
      cf << Transaction.new( 1100.0, date: '2023-01-30'.to_date)
```
Ends up being this:
```
      cf = Cashflow.new
      cf << Transaction.new( 500.0, date: '2022-12-13'.to_date)
      cf << Transaction.new( 1100.0, date: '2023-01-30'.to_date)
```

**Comment by davidalejandroaguilar** [comment]
Thanks for the follow-up and the commit 😃
