### ISSUE TITLE
Error in production

### ISSUE THREAD

**Issue by jordangraft** [tubedude/xirr#3]
Working on a Digital Ocean droplet with Ubuntu 14.04 with Unicorn and Nginx, we encountered this error in production:

```
Define INLINEDIR or HOME in your environment and try again
```

Came up in the Unicorn log.  It's an existing deployment and the error came up with the ```xirr``` gem and then went away when we commented it out.  Any thoughts on the workaround?  Works fine in development on Mac OS but failed in production.  Googling around for the error didn't yield much in the way of solutions.  Found this on Stack http://stackoverflow.com/questions/6051399/rake-task-says-define-inlinedir-or-home-in-your-environment-and-try-again-how but wanted to see what you thought before just adding env variables without understanding what's causing the problem.

**Comment by tubedude** [comment]
I've only used in production in Heroku without any problem. It seems this error is being generated by the Ruby Inline. I'll make a branch that does not use it so you can test. The down side is that it will have a huge impact in the performance.

**Comment by tubedude** [comment]
Try this branch: https://github.com/tubedude/xirr/tree/no_inline
I removed Ruby Inline and changed default method to Bisection.
Please let me know what happens.

**Comment by jordangraft** [comment]
Ah thank you that's very helpful. I will try it this morning/afternoon and
get back to you.

Now that I know it's Ruby Inline, I will also try some of the recommended
fixes on our droplet using the master branch as well:
https://www.ruby-forum.com/topic/159766.

**Comment by tubedude** [comment]
@jordangraft : indeed maybe this simple env should solve the issue. If you can't change it you can try the branch.

**Comment by jordangraft** [comment]
Sorry for the delay!

Last night, we switched to the ```no-inline``` branch and it works great in production.  We are only doing a few calculations (2 or 3) with it on a couple of pages so not having any speed issues.

Later tonight I will try the master and setting the env variables.

Thanks so much!
