### ISSUE TITLE
Discrepancy in gem value and google spreadsheet value 

### ISSUE THREAD

**Issue by xichen27** [tubedude/xirr#4]
cf = Cashflow.new
cf << Transaction.new(-10000,  date: '2014-04-015'.to_date)
cf << Transaction.new(-305.6,  date: '2014-05-015'.to_date)
cf << Transaction.new( 500, date: '2014-10-19'.to_date)
cf.xirr
-0.1001195E1 [BigDecimal]

However, the result in google spreadsheet is -0.996814607

**Comment by tubedude** [comment]
Running on master I've got the following value: -0.997374 which is close enough.
I see in your example you got the date wrong, but I'm assuming the dates to be 2014-04-15 and 2014-05-15. I'll make a new commit including your scenario in the tests.

**Comment by xichen27** [comment]
It works for me until I reduce the third value to 500. I just updated the gem version. Instead of getting a <-100 value, I am getting 0.0. I am assuming it's the same problem. Would really appreciate if you could let me know what I am doing wrong here. Thanks in advance.

**Comment by xichen27** [comment]
Actually the second value is 305.6 not -305.6.

**Comment by tubedude** [comment]
Ok. Now it is real closed. I posted an updated in which I changed the limits at the negative side.
https://github.com/tubedude/xirr/commit/a068b21a9433420617d8c753ec4208678c3943d3

**Comment by xichen27** [comment]
Thanks. It works now.
